/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IPaymentGateway, IPaymentGatewayInterface } from "../../PrivacyPool.sol/IPaymentGateway.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "invoiceId",
        "type": "bytes32"
      }
    ],
    "name": "getAmount",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "invoiceId",
        "type": "bytes32"
      }
    ],
    "name": "getToken",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "invoiceId",
        "type": "bytes32"
      }
    ],
    "name": "payInvoice",
    "outputs": [
      {
        "internalType": "address",
        "name": "merchant",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IPaymentGateway__factory {
    static readonly abi = _abi;
    static createInterface(): IPaymentGatewayInterface {
      return new Interface(_abi) as IPaymentGatewayInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IPaymentGateway {
      return new Contract(address, _abi, runner) as unknown as IPaymentGateway;
    }
  }
  