/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IPaymentGatewayInterface extends Interface {
    getFunction(nameOrSignature: "getAmount" | "getToken" | "payInvoice"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getAmount', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getToken', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'payInvoice', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'getAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payInvoice', data: BytesLike): Result;
  }

  

  export interface IPaymentGateway extends BaseContract {
    
    connect(runner?: ContractRunner | null): IPaymentGateway;
    waitForDeployment(): Promise<this>;

    interface: IPaymentGatewayInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getAmount: TypedContractMethod<
      [invoiceId: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getToken: TypedContractMethod<
      [invoiceId: BytesLike, ],
      [string],
      'view'
    >
    

    
    payInvoice: TypedContractMethod<
      [invoiceId: BytesLike, ],
      [string],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getAmount'): TypedContractMethod<
      [invoiceId: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getToken'): TypedContractMethod<
      [invoiceId: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'payInvoice'): TypedContractMethod<
      [invoiceId: BytesLike, ],
      [string],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }