/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface PrivacyPoolInterface extends Interface {
    getFunction(nameOrSignature: "addToken" | "deposit" | "getCommitment" | "isSpent" | "owner" | "paymentGateway" | "poolBalance" | "relayer" | "removeToken" | "renounceOwnership" | "setPaymentGateway" | "supportedTokens" | "transferOwnership" | "updateRelayer" | "verifier" | "withdrawAndPay"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Deposited" | "GatewayUpdated" | "OwnershipTransferred" | "RelayerUpdated" | "TokenAdded" | "TokenRemoved" | "WithdrawalRelayed"): EventFragment;

    encodeFunctionData(functionFragment: 'addToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'deposit', values: [AddressLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCommitment', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'isSpent', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'paymentGateway', values?: undefined): string;
encodeFunctionData(functionFragment: 'poolBalance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'relayer', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setPaymentGateway', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'supportedTokens', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateRelayer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verifier', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawAndPay', values: [BytesLike, BytesLike, [BigNumberish, BigNumberish], [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]], [BigNumberish, BigNumberish], [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]]): string;

    decodeFunctionResult(functionFragment: 'addToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCommitment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isSpent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paymentGateway', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'poolBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'relayer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPaymentGateway', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportedTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateRelayer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawAndPay', data: BytesLike): Result;
  }

  
    export namespace DepositedEvent {
      export type InputTuple = [commitment: BytesLike, depositor: AddressLike, token: AddressLike, amount: BigNumberish];
      export type OutputTuple = [commitment: string, depositor: string, token: string, amount: bigint];
      export interface OutputObject {commitment: string, depositor: string, token: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GatewayUpdatedEvent {
      export type InputTuple = [newGateway: AddressLike];
      export type OutputTuple = [newGateway: string];
      export interface OutputObject {newGateway: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RelayerUpdatedEvent {
      export type InputTuple = [newRelayer: AddressLike];
      export type OutputTuple = [newRelayer: string];
      export interface OutputObject {newRelayer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenAddedEvent {
      export type InputTuple = [token: AddressLike];
      export type OutputTuple = [token: string];
      export interface OutputObject {token: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenRemovedEvent {
      export type InputTuple = [token: AddressLike];
      export type OutputTuple = [token: string];
      export interface OutputObject {token: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawalRelayedEvent {
      export type InputTuple = [nullifier: BytesLike, invoiceId: BytesLike, merchant: AddressLike, token: AddressLike, amount: BigNumberish];
      export type OutputTuple = [nullifier: string, invoiceId: string, merchant: string, token: string, amount: bigint];
      export interface OutputObject {nullifier: string, invoiceId: string, merchant: string, token: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PrivacyPool extends BaseContract {
    
    connect(runner?: ContractRunner | null): PrivacyPool;
    waitForDeployment(): Promise<this>;

    interface: PrivacyPoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addToken: TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    deposit: TypedContractMethod<
      [token: AddressLike, commitment: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getCommitment: TypedContractMethod<
      [commitment: BytesLike, ],
      [[string, string, bigint, boolean] & {depositor: string, token: string, amount: bigint, exists: boolean }],
      'view'
    >
    

    
    isSpent: TypedContractMethod<
      [nullifier: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    paymentGateway: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    poolBalance: TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    relayer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    removeToken: TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setPaymentGateway: TypedContractMethod<
      [_gateway: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportedTokens: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateRelayer: TypedContractMethod<
      [newRelayer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifier: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    withdrawAndPay: TypedContractMethod<
      [nullifier: BytesLike, invoiceId: BytesLike, a: [BigNumberish, BigNumberish], b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]], c: [BigNumberish, BigNumberish], publicSignals: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish], ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addToken'): TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [token: AddressLike, commitment: BytesLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCommitment'): TypedContractMethod<
      [commitment: BytesLike, ],
      [[string, string, bigint, boolean] & {depositor: string, token: string, amount: bigint, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'isSpent'): TypedContractMethod<
      [nullifier: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paymentGateway'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'poolBalance'): TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'relayer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'removeToken'): TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPaymentGateway'): TypedContractMethod<
      [_gateway: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportedTokens'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateRelayer'): TypedContractMethod<
      [newRelayer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifier'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawAndPay'): TypedContractMethod<
      [nullifier: BytesLike, invoiceId: BytesLike, a: [BigNumberish, BigNumberish], b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]], c: [BigNumberish, BigNumberish], publicSignals: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish], ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Deposited'): TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
getEvent(key: 'GatewayUpdated'): TypedContractEvent<GatewayUpdatedEvent.InputTuple, GatewayUpdatedEvent.OutputTuple, GatewayUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RelayerUpdated'): TypedContractEvent<RelayerUpdatedEvent.InputTuple, RelayerUpdatedEvent.OutputTuple, RelayerUpdatedEvent.OutputObject>;
getEvent(key: 'TokenAdded'): TypedContractEvent<TokenAddedEvent.InputTuple, TokenAddedEvent.OutputTuple, TokenAddedEvent.OutputObject>;
getEvent(key: 'TokenRemoved'): TypedContractEvent<TokenRemovedEvent.InputTuple, TokenRemovedEvent.OutputTuple, TokenRemovedEvent.OutputObject>;
getEvent(key: 'WithdrawalRelayed'): TypedContractEvent<WithdrawalRelayedEvent.InputTuple, WithdrawalRelayedEvent.OutputTuple, WithdrawalRelayedEvent.OutputObject>;

    filters: {
      
      'Deposited(bytes32,address,address,uint256)': TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
      Deposited: TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
    

      'GatewayUpdated(address)': TypedContractEvent<GatewayUpdatedEvent.InputTuple, GatewayUpdatedEvent.OutputTuple, GatewayUpdatedEvent.OutputObject>;
      GatewayUpdated: TypedContractEvent<GatewayUpdatedEvent.InputTuple, GatewayUpdatedEvent.OutputTuple, GatewayUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RelayerUpdated(address)': TypedContractEvent<RelayerUpdatedEvent.InputTuple, RelayerUpdatedEvent.OutputTuple, RelayerUpdatedEvent.OutputObject>;
      RelayerUpdated: TypedContractEvent<RelayerUpdatedEvent.InputTuple, RelayerUpdatedEvent.OutputTuple, RelayerUpdatedEvent.OutputObject>;
    

      'TokenAdded(address)': TypedContractEvent<TokenAddedEvent.InputTuple, TokenAddedEvent.OutputTuple, TokenAddedEvent.OutputObject>;
      TokenAdded: TypedContractEvent<TokenAddedEvent.InputTuple, TokenAddedEvent.OutputTuple, TokenAddedEvent.OutputObject>;
    

      'TokenRemoved(address)': TypedContractEvent<TokenRemovedEvent.InputTuple, TokenRemovedEvent.OutputTuple, TokenRemovedEvent.OutputObject>;
      TokenRemoved: TypedContractEvent<TokenRemovedEvent.InputTuple, TokenRemovedEvent.OutputTuple, TokenRemovedEvent.OutputObject>;
    

      'WithdrawalRelayed(bytes32,bytes32,address,address,uint256)': TypedContractEvent<WithdrawalRelayedEvent.InputTuple, WithdrawalRelayedEvent.OutputTuple, WithdrawalRelayedEvent.OutputObject>;
      WithdrawalRelayed: TypedContractEvent<WithdrawalRelayedEvent.InputTuple, WithdrawalRelayedEvent.OutputTuple, WithdrawalRelayedEvent.OutputObject>;
    
    };
  }