/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface PaymentGatewayInterface extends Interface {
    getFunction(nameOrSignature: "createInvoice" | "getAmount" | "getInvoice" | "getMerchant" | "getToken" | "isPaid" | "payInvoice" | "privacyPool"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "InvoiceCreated" | "InvoicePaid"): EventFragment;

    encodeFunctionData(functionFragment: 'createInvoice', values: [BytesLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAmount', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getInvoice', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getMerchant', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getToken', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'isPaid', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'payInvoice', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'privacyPool', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'createInvoice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getInvoice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMerchant', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isPaid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payInvoice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'privacyPool', data: BytesLike): Result;
  }

  
    export namespace InvoiceCreatedEvent {
      export type InputTuple = [invoiceId: BytesLike, merchant: AddressLike, token: AddressLike, amount: BigNumberish];
      export type OutputTuple = [invoiceId: string, merchant: string, token: string, amount: bigint];
      export interface OutputObject {invoiceId: string, merchant: string, token: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InvoicePaidEvent {
      export type InputTuple = [invoiceId: BytesLike, merchant: AddressLike, token: AddressLike, amount: BigNumberish];
      export type OutputTuple = [invoiceId: string, merchant: string, token: string, amount: bigint];
      export interface OutputObject {invoiceId: string, merchant: string, token: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PaymentGateway extends BaseContract {
    
    connect(runner?: ContractRunner | null): PaymentGateway;
    waitForDeployment(): Promise<this>;

    interface: PaymentGatewayInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createInvoice: TypedContractMethod<
      [invoiceId: BytesLike, token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAmount: TypedContractMethod<
      [invoiceId: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getInvoice: TypedContractMethod<
      [invoiceId: BytesLike, ],
      [[string, string, bigint, boolean, boolean] & {merchant: string, token: string, amount: bigint, paid: boolean, exists: boolean }],
      'view'
    >
    

    
    getMerchant: TypedContractMethod<
      [invoiceId: BytesLike, ],
      [string],
      'view'
    >
    

    
    getToken: TypedContractMethod<
      [invoiceId: BytesLike, ],
      [string],
      'view'
    >
    

    
    isPaid: TypedContractMethod<
      [invoiceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    payInvoice: TypedContractMethod<
      [invoiceId: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    privacyPool: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createInvoice'): TypedContractMethod<
      [invoiceId: BytesLike, token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAmount'): TypedContractMethod<
      [invoiceId: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getInvoice'): TypedContractMethod<
      [invoiceId: BytesLike, ],
      [[string, string, bigint, boolean, boolean] & {merchant: string, token: string, amount: bigint, paid: boolean, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getMerchant'): TypedContractMethod<
      [invoiceId: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getToken'): TypedContractMethod<
      [invoiceId: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isPaid'): TypedContractMethod<
      [invoiceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'payInvoice'): TypedContractMethod<
      [invoiceId: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'privacyPool'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'InvoiceCreated'): TypedContractEvent<InvoiceCreatedEvent.InputTuple, InvoiceCreatedEvent.OutputTuple, InvoiceCreatedEvent.OutputObject>;
getEvent(key: 'InvoicePaid'): TypedContractEvent<InvoicePaidEvent.InputTuple, InvoicePaidEvent.OutputTuple, InvoicePaidEvent.OutputObject>;

    filters: {
      
      'InvoiceCreated(bytes32,address,address,uint256)': TypedContractEvent<InvoiceCreatedEvent.InputTuple, InvoiceCreatedEvent.OutputTuple, InvoiceCreatedEvent.OutputObject>;
      InvoiceCreated: TypedContractEvent<InvoiceCreatedEvent.InputTuple, InvoiceCreatedEvent.OutputTuple, InvoiceCreatedEvent.OutputObject>;
    

      'InvoicePaid(bytes32,address,address,uint256)': TypedContractEvent<InvoicePaidEvent.InputTuple, InvoicePaidEvent.OutputTuple, InvoicePaidEvent.OutputObject>;
      InvoicePaid: TypedContractEvent<InvoicePaidEvent.InputTuple, InvoicePaidEvent.OutputTuple, InvoicePaidEvent.OutputObject>;
    
    };
  }